---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: content/kh/blog
  label: Khmer Articles
  create: all
  match: "**/*"
- type: directory
  path: content/en/blog
  label: English Articles
  create: all
  match: "**/*"
- type: directory
  path: content/en/project
  label: English Project
  create: all
  match: "**/*"
- type: directory
  path: content/kh/project
  label: Khmer Project
  create: all
  match: "**/*"
upload_dir: static
public_path: "/static"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
